//
// Decorated.java
// Autogenerated by Plank (https://pinterest.github.io/plank/)
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import com.pinterest.models.custom.MyCustomClass;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;

/**
 * Autogenerated by Plank (https://pinterest.github.io/plank/)
 * DO NOT EDIT - EDITS WILL BE OVERWRITTEN
**/
public class Decorated {

    public static final String TYPE = "decorated";

    @SerializedName("externalType") private @Nullable MyCustomClass externalType;
    @SerializedName("name") private @Nullable String name;

    private static final int EXTERNALTYPE_INDEX = 0;
    private static final int NAME_INDEX = 1;

    private boolean[] _bits;

    public Decorated() {
        this._bits = new boolean[2];
    }

    private Decorated(
        @Nullable MyCustomClass externalType,
        @Nullable String name,
        boolean[] _bits
    ) {
        this.externalType = externalType;
        this.name = name;
        this._bits = _bits;
    }

    @NonNull
    public static Decorated.Builder builder() {
        return new Decorated.Builder();
    }

    @NonNull
    public Decorated.Builder toBuilder() {
        return new Decorated.Builder(this);
    }

    @NonNull
    public Decorated mergeFrom(@NonNull Decorated model) {
        if (this == model) {
            return this;
        }
        Decorated.Builder builder = this.toBuilder();
        builder.mergeFrom(model);
        return builder.build();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Decorated that = (Decorated) o;
        return Objects.equals(this.externalType, that.externalType) &&
        Objects.equals(this.name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(externalType,
        name);
    }

    public @Nullable MyCustomClass getExternalType() {
        return this.externalType;
    }

    public @Nullable String getName() {
        return this.name;
    }

    public boolean getExternalTypeIsSet() {
        return this._bits.length > EXTERNALTYPE_INDEX && this._bits[EXTERNALTYPE_INDEX];
    }

    public boolean getNameIsSet() {
        return this._bits.length > NAME_INDEX && this._bits[NAME_INDEX];
    }

    public static class Builder {

        private @Nullable MyCustomClass externalType;
        private @Nullable String name;

        private boolean[] _bits;

        private Builder() {
            this._bits = new boolean[2];
        }

        private Builder(@NonNull Decorated model) {
            this.externalType = model.externalType;
            this.name = model.name;
            this._bits = Arrays.copyOf(model._bits, model._bits.length);
        }

        @NonNull
        public Builder setExternalType(@Nullable MyCustomClass value) {
            this.externalType = value;
            if (this._bits.length > EXTERNALTYPE_INDEX) {
                this._bits[EXTERNALTYPE_INDEX] = true;
            }
            return this;
        }

        @NonNull
        public Builder setName(@Nullable String value) {
            this.name = value;
            if (this._bits.length > NAME_INDEX) {
                this._bits[NAME_INDEX] = true;
            }
            return this;
        }

        public @Nullable MyCustomClass getExternalType() {
            return this.externalType;
        }

        public @Nullable String getName() {
            return this.name;
        }

        @NonNull
        public Decorated build() {
            return new Decorated(
            this.externalType,
            this.name,
            this._bits
            );
        }

        public void mergeFrom(@NonNull Decorated model) {
            if (model._bits.length > EXTERNALTYPE_INDEX && model._bits[EXTERNALTYPE_INDEX]) {
                this.externalType = model.externalType;
                this._bits[EXTERNALTYPE_INDEX] = true;
            }
            if (model._bits.length > NAME_INDEX && model._bits[NAME_INDEX]) {
                this.name = model.name;
                this._bits[NAME_INDEX] = true;
            }
        }
    }

    public static class DecoratedTypeAdapterFactory implements TypeAdapterFactory {

        @Nullable
        @Override
        public <T> TypeAdapter<T> create(@NonNull Gson gson, @NonNull TypeToken<T> typeToken) {
            if (!Decorated.class.isAssignableFrom(typeToken.getRawType())) {
                return null;
            }
            return (TypeAdapter<T>) new DecoratedTypeAdapter(gson);
        }
    }

    private static class DecoratedTypeAdapter extends TypeAdapter<Decorated> {

        private final Gson gson;
        private TypeAdapter<MyCustomClass> myCustomClassTypeAdapter;
        private TypeAdapter<String> stringTypeAdapter;

        DecoratedTypeAdapter(Gson gson) {
            this.gson = gson;
        }

        @Override
        public void write(@NonNull JsonWriter writer, Decorated value) throws IOException {
            if (value == null) {
                writer.nullValue();
                return;
            }
            writer.beginObject();
            if (value._bits.length > EXTERNALTYPE_INDEX && value._bits[EXTERNALTYPE_INDEX]) {
                if (this.myCustomClassTypeAdapter == null) {
                    this.myCustomClassTypeAdapter = this.gson.getAdapter(MyCustomClass.class).nullSafe();
                }
                this.myCustomClassTypeAdapter.write(writer.name("externalType"), value.externalType);
            }
            if (value._bits.length > NAME_INDEX && value._bits[NAME_INDEX]) {
                if (this.stringTypeAdapter == null) {
                    this.stringTypeAdapter = this.gson.getAdapter(String.class).nullSafe();
                }
                this.stringTypeAdapter.write(writer.name("name"), value.name);
            }
            writer.endObject();
        }

        @Nullable
        @Override
        public Decorated read(@NonNull JsonReader reader) throws IOException {
            if (reader.peek() == JsonToken.NULL) {
                reader.nextNull();
                return null;
            }
            Builder builder = Decorated.builder();
            reader.beginObject();
            while (reader.hasNext()) {
                String name = reader.nextName();
                switch (name) {
                    case ("externalType"):
                        if (this.myCustomClassTypeAdapter == null) {
                            this.myCustomClassTypeAdapter = this.gson.getAdapter(MyCustomClass.class).nullSafe();
                        }
                        builder.setExternalType(this.myCustomClassTypeAdapter.read(reader));
                        break;
                    case ("name"):
                        if (this.stringTypeAdapter == null) {
                            this.stringTypeAdapter = this.gson.getAdapter(String.class).nullSafe();
                        }
                        builder.setName(this.stringTypeAdapter.read(reader));
                        break;
                    default:
                        reader.skipValue();
                        break;
                }
            }
            reader.endObject();
            return builder.build();
        }
    }
}
