//
// Decorated.h
// Autogenerated by Plank (https://pinterest.github.io/plank/)
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class DecoratedBuilder;

@class MyCustomClass;

NS_ASSUME_NONNULL_BEGIN

@interface Decorated : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, strong, readonly) MyCustomClass * externalType;
@property (nullable, nonatomic, copy, readonly) NSString * name;

+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary error:(NSError *__autoreleasing *)error;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary error:(NSError *__autoreleasing *)error;
- (instancetype)initWithBuilder:(DecoratedBuilder *)builder;
- (instancetype)initWithBuilder:(DecoratedBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(DecoratedBuilder *builder))block;
- (BOOL)isEqualToDecorated:(Decorated *)anObject;
- (instancetype)mergeWithModel:(Decorated *)modelObject;
- (instancetype)mergeWithModel:(Decorated *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
- (BOOL)isExternalTypeSet;
- (BOOL)isNameSet;
@end

@interface DecoratedBuilder : NSObject
@property (nullable, nonatomic, strong, readwrite) MyCustomClass * externalType;
@property (nullable, nonatomic, copy, readwrite) NSString * name;

- (instancetype)initWithModel:(Decorated *)modelObject;
- (Decorated *)build;
- (void)mergeWithModel:(Decorated *)modelObject;
@end

NS_ASSUME_NONNULL_END
